### ISSUE TITLE
Tags for events

### ISSUE THREAD

**Issue by mamhoff** [BiteKollektiv/webcal#22]
Events need tags. Can I make some?

**Comment by carolinagc** [comment]
There is a nice gem for tagging, in case you need it
https://github.com/mbleigh/acts-as-taggable-on

**Comment by phansch** [comment]
:+1:

**Comment by mamhoff** [comment]
I think I'll rather use https://github.com/pat/gutentag - it's a lot simpler. :)

**Comment by phansch** [comment]
Done with https://github.com/BatchZero/webcal/commit/ee4abbb9f0cd7190a6353806db8d03158c123101. :sparkles:
