### ISSUE TITLE
Problematic Calendar Names

### ISSUE THREAD

**Issue by vaxr** [BiteKollektiv/webcal#44]
Trying to download an .ics from a calendar whose name includes spaces:

```
undefined method `to_ical' for nil:NilClass
```

**Comment by phansch** [comment]
Very strange, I can't seem to reproduce this. Can you tell me if importing works you?

**Comment by vaxr** [comment]
Sorry, today I cannot reproduce it either. Maybe a reboot fixed it.
Import works.

**Comment by phansch** [comment]
Awesome, thanks. I will close this issue then. If you manage to reproduce it, just comment again.
